*** Settings ***
Resource          ..${/}subfolder-1${/}a_sub.resource
Resource          ..${/}subfolder-2${/}a_sub.resource
Resource          ..${/}subfolder-3${/}a_sub.resource
Resource          ..${/}subfolder-4${/}a_sub.resource
Resource          ..${/}subfolder-5${/}a_sub.resource
Resource          ..${/}subfolder-6${/}a_sub.resource
Resource          ..${/}subfolder-7${/}a_sub.resource
Resource          ..${/}subfolder-8${/}a_sub.resource
Resource          ..${/}subfolder-9${/}a_sub.resource
Resource          ..${/}subfolder-20${/}a_sub.resource
Resource          ..${/}subfolder-21${/}a_sub.resource
Resource          ..${/}subfolder-22${/}a_sub.resource
Resource          ..${/}subfolder-23${/}a_sub.resource
Resource          ..${/}subfolder-24${/}a_sub.resource
Resource          ..${/}subfolder-25${/}a_sub.resource
Resource          ..${/}subfolder-26${/}a_sub.resource
Resource          ..${/}subfolder-27${/}a_sub.resource
Resource          ..${/}subfolder-28${/}a_sub.resource
Resource          ..${/}subfolder-29${/}a_sub.resource
Resource          ..${/}subfolder-30${/}a_sub.resource
Resource          ..${/}subfolder-31${/}a_sub.resource
Resource          ..${/}subfolder-32${/}a_sub.resource
Resource          ..${/}subfolder-33${/}a_sub.resource
Resource          ..${/}subfolder-34${/}a_sub.resource
Resource          ..${/}subfolder-35${/}a_sub.resource

*** Keywords ***
