*** Settings ***
Library          DateTime
Resource         ../../resources/Generic_Resources/generic.resource
Resource         ../../resources/Generic_Resources/fetch_metadata.resource
Resource         ../../resources/Generic_Resources/fetch_data.resource
Resource         ../../resources/Kiwi_Resources/page_kiwi.resource
Resource         ../../resources/Kiwi_Resources/marking_timecharts.resource
