*** Settings ***
Resource          ..${/}subfolder-1${/}a_sub.resource
Resource          ..${/}subfolder-2${/}a_sub.resource
Resource          ..${/}subfolder-3${/}a_sub.resource
Resource          ..${/}subfolder-4${/}a_sub.resource
Resource          ..${/}subfolder-5${/}a_sub.resource
Resource          ..${/}subfolder-6${/}a_sub.resource
Resource          ..${/}subfolder-7${/}a_sub.resource
Resource          ..${/}subfolder-8${/}a_sub.resource
Resource          ..${/}subfolder-9${/}a_sub.resource

*** Keywords ***
