*** Settings ***
Resource          ..${/}subfolder-1${/}a_sub.resource
Resource          ..${/}subfolder-2${/}a_sub.resource
Resource          ..${/}subfolder-3${/}a_sub.resource
Resource          ..${/}subfolder-4${/}a_sub.resource
Resource          ..${/}subfolder-5${/}a_sub.resource
Resource          ..${/}subfolder-6${/}a_sub.resource
Resource          ..${/}subfolder-7${/}a_sub.resource
Resource          ..${/}subfolder-8${/}a_sub.resource
Resource          ..${/}subfolder-9${/}a_sub.resource
Resource          ..${/}subfolder-10${/}a_sub.resource
Resource          ..${/}subfolder-11${/}a_sub.resource
Resource          ..${/}subfolder-12${/}a_sub.resource
Resource          ..${/}subfolder-13${/}a_sub.resource
Resource          ..${/}subfolder-14${/}a_sub.resource
Resource          ..${/}subfolder-15${/}a_sub.resource
Resource          ..${/}subfolder-16${/}a_sub.resource
Resource          ..${/}subfolder-17${/}a_sub.resource
Resource          ..${/}subfolder-18${/}a_sub.resource
Resource          ..${/}subfolder-19${/}a_sub.resource

*** Keywords ***
