*** Settings ***
Library          DateTime
Resource         ../../resources/Generic_Resources/generic.resource
Resource         ../../resources/Generic_Resources/fetch_metadata.resource
Resource         ../../resources/Generic_Resources/fetch_data.resource
Resource         ../../resources/KPIIA_Resources/page_kpiia.resource
Resource         ../../resources/KPIIA_Resources/marking_timecharts.resource