#!/bin/bash
#
# A hook script to update the version numbers
#  post-commit

# git rev-parse --abbrev-ref HEAD
version=$(git rev-parse --abbrev-ref HEAD)
# version=$(git tag -l v* |tail -1)
# echo "version: $version"
if [[ "$version" =~ v[0-9]\. ]]; then
	# echo "version: $version"
	# numver=$(echo $version | sed -E 's/v(.*)/\1/')
	# numver=$(echo $version | sed -E 's/v(.*)-.*/\1/')
	numver=$(echo $version | sed -E 's/v([^-]*)/\1/')
	# echo "numver: $numver"
	sed -i '' -e "s/version *= *\"[^\"]*\"/version=\"${numver}\"/" $(find . -name "*.py")
	#	Version Test
	sed -i '' -e "s/#    Version .*/#    Version ${numver}/" $(find . -name "*.py")
	# git commit -m "Update version to ${version}"
	if ! git diff-index --quiet HEAD --; then
		# echo "commit: Update version to $version"
		git add $(find . -name "*.py")
	    git commit -m "Update version to ${numver}"
	fi
# else
# 	echo "version ($version) not pattern 'v[0-9]\.'"
fi



# if [[ "$date" =~ "[0-9]\{8\}" ]]; then
#     echo "Valid date"
# else
#     echo "Invalid date"
# fi
