*** Settings ***
Resource          ..${/}subfolder-10${/}a_sub.resource
Resource          ..${/}subfolder-11${/}a_sub.resource
Resource          ..${/}subfolder-12${/}a_sub.resource
Resource          ..${/}subfolder-13${/}a_sub.resource
Resource          ..${/}subfolder-14${/}a_sub.resource
Resource          ..${/}subfolder-15${/}a_sub.resource
Resource          ..${/}subfolder-16${/}a_sub.resource
Resource          ..${/}subfolder-17${/}a_sub.resource
Resource          ..${/}subfolder-18${/}a_sub.resource
Resource          ..${/}subfolder-19${/}a_sub.resource
Resource          ..${/}subfolder-20${/}a_sub.resource
Resource          ..${/}subfolder-21${/}a_sub.resource
Resource          ..${/}subfolder-22${/}a_sub.resource
Resource          ..${/}subfolder-23${/}a_sub.resource
Resource          ..${/}subfolder-24${/}a_sub.resource
Resource          ..${/}subfolder-25${/}a_sub.resource
Resource          ..${/}subfolder-26${/}a_sub.resource
Resource          ..${/}subfolder-27${/}a_sub.resource
Resource          ..${/}subfolder-28${/}a_sub.resource
Resource          ..${/}subfolder-29${/}a_sub.resource
Resource          ..${/}subfolder-30${/}a_sub.resource
Resource          ..${/}subfolder-31${/}a_sub.resource
Resource          ..${/}subfolder-32${/}a_sub.resource
Resource          ..${/}subfolder-33${/}a_sub.resource
Resource          ..${/}subfolder-34${/}a_sub.resource
Resource          ..${/}subfolder-35${/}a_sub.resource

*** Keywords ***
