---
name: Package Test Publish

on:
  push:
  pull_request:
    types: [opened, reopened]

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

jobs:
  Package_For_PIP:
    uses: ./.github/workflows/Package.yaml

  # Regression_Tests:
  #   needs:
  #     - Package_For_PIP
  #   uses: ./.github/workflows/Regression_Tests.yaml

  Regression_Tests_Agent:
    if: needs.Package_For_PIP.outputs.runagent == 'true'
    needs:
      - Package_For_PIP
    uses: ./.github/workflows/Regression_Tests_Agent.yaml

  Regression_Tests_Manager:
    if: needs.Package_For_PIP.outputs.runmanager == 'true'
    needs:
      - Package_For_PIP
    uses: ./.github/workflows/Regression_Tests_Manager.yaml

  Regression_Tests_Reporter:
    if: needs.Package_For_PIP.outputs.runreporter == 'true'
    needs:
      - Package_For_PIP
    uses: ./.github/workflows/Regression_Tests_Reporter.yaml

  Publish_Package:
    if: github.repository_owner == 'damies13' && needs.Package_For_PIP.outputs.isrelease == 1
    # if: github.repository_owner == 'damies13'
    needs:
    - Package_For_PIP
    # - Regression_Tests
    - Regression_Tests_Agent
    - Regression_Tests_Manager
    - Regression_Tests_Reporter
    uses: ./.github/workflows/Publish.yaml
